const modules = {
  ANALYSE: "Analyse",
  ATELIER_INFORMATIQUES: "Atelier Informatiques",
  AUTOMATIQUE: "Automatique",
  AUTOMATIQUE_ET_ELECTRONIQUE: "Automatique et Electronique",
  CAPTEURS_ET_SIGNAUX: "Capteurs et signaux",
  CULTURE_ENTREPRISE_1: "Langues et Culture d'Entreprise 1",
  CULTURE_ENTREPRISE_2: "Langues et Culture d'Entreprise 2",
  DEVELOPPEMENT: "Développement",
  DEVELOPPEMENT_LOGICIEL: "Développement Logiciel",
  ELECTRICITE: "Electricité",
  ELECTRONIQUE_AUTOMATIQUE: "Electronique - Automatique",
  ELECTRONIQUE_ELECTROTECHNIQUE: "Electronique - Electrotechnique",
  ELECTRONIQUE_PUISSANCE: "Electronique de puissance",
  ELECTROMECANIQUE: "Electromécanique",
  FONDAMENTAL: "Fondamental",
  GESTION_INDUSTRIELLE: "Gestion industrielle",
  INFORMATIQUE: "Informatique",
  INFORMATIQUE_1: "Informatique 1",
  INFORMATIQUE_2: "Informatique 2",
  INFORMATIQUE_APPLIQUEE: "Infomatique appliquée",
  INGENIERIE_SCIENCE_DONNEES: "Ingénierie et Science des Données",
  INGENIERIES_DONNEES: "Ingénieries des données",
  INGENIEURIE_SYSTEMES_INDUSTRIELS: "Ingénieurie des Systèmes Industriels",
  INGENIEURIE_SYSTEMES_EMBARQUES: "Ingénieurie des systèmes embarqués",
  INSTRUMENTATION: "Instrumentation",
  INSTRUMENTATION_MAINTENANCE: "Instrumentation et Maintenance",
  INSTRUMENTATION_SYSTEMES_INTELLIGENTS:
    "Instrumentation et Systèmes intelligents",
  LANGUES_CULTURE_ENTREPRISE_1: "Langues et Culture d'Entreprise 1",
  LANGUES_CULTURE_ENTREPRISE_2: "Langues et Culture d'Entreprise 2",
  MACHINES_SYSTEMES: "Machines et Systèmes",
  MANAGEMENT_INGENIERIE: "Management en ingénierie",
  MATERIEL_SYSTEMES: "Matériel et Systèmes",
  MATHEMATIQUES: "Mathématiques",
  MATHEMATIQUES_1: "Mathématiques 1",
  MATHEMATIQUES_2: "Mathématiques 2",
  MATHEMATIQUES_APPLIQUEES_ENVIRONNEMENT_INDUSTRIEL:
    "Mathématiques appliquées et Environnement industriel",
  MATHEMATIQUES_INFORMATIQUES: "Mathématiques et Informatiques",
  MATHEMATIQUES_POUR_INGENIEUR: "Mathématiques pour l'ingénieur",
  MECANIQUE_AUTOMATIQUE: "Mécanique - Automatique",
  MECANIQUE_ELECTROTECHNIQUE: "Mécanique et Electrotechnique",
  METHODES_PRODUCTIQUE: "Méthodes et Productique",
  ONDES_MECANIQUE: "Ondes et Mécanique",
  OPTION_AERODYNAMIQUE_INTELLIGENCE_ARTIFICIELLE:
    "Option: Aérodynamique & Intelligence Artificielle",
  OPTION_CLOUD: "Option: Cloud",
  OPTION_DEVOPS: "Option: DevOps",
  OPTION_IMAGE_VISION_APPRENTISSAGE: "Option: Image, Vision et apprentissage",
  OPTION_INGENIERIE_SYSTEMES_EMBARQUES:
    "Option: Ingénieurie des systèmes embarqués",
  OPTION_INGENIERIE_SYSTEMES_INDUSTRIELS:
    "Option: Ingénieurie des Systèmes Industriels",
  OPTION_INSTRUMENTATION_SYSTEME_INTELLIGENTS:
    "Option: Instrumentation et Système Intelligents",
  OPTION_INSTRUMENTATION_SYSTEMES_INTELLIGENTS:
    "Option: Instrumentation et Systèmes intelligents",
  OPTION_MAINTENANCE_QUALITE: "Option: Maintenance et Qualité",
  OPTION_METHODS_PRODUCTIQUE: "Option: Méthodes et Productique",
  OPTION_SECURITE: "Option: Sécurité",
  OPTION_IOT: "Option: IoT",
  PROJET: "Projet",
  RESEAUX: "Réseaux",
  RESEAUX_TELECOMMUNICATIONS: "Réseaux et Télécommunications",
  ROBOTIQUE: "Robotique",
  SIGNAL_PROPAGATION: "Signal et Propagation",
  SYSTEME_INTELLIGENTS: "Système Intelligents",
  SYSTEMES_RESEAUX: "Systèmes et Réseaux",
  SYSTEMES_TELECOMMUNICATIONS: "Systèmes et Télécommunications",
  SYSTEME_APPLICATIONS: "Système et Applications",
  SYSTEMES_INFORMATION_1: "Systèmes d'information 1",
  SYSTEMES_INFORMATION_2: "Systèmes d'information 2",
  TELECOMMUNICATIONS: "Télécommunications",
  TRAITEMENT_INFORMATION_INTELLIGENCE_ARTIFICIELLE_1:
    "Traitement de l'information et Intelligence Artificielle 1",
  TRAITEMENT_INFORMATION_INTELLIGENCE_ARTIFICIELLE_2:
    "Traitement de l'information et Intelligence Artificielle 2",
};

export default modules;
